default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

# development:
#   <<: *default
#   database: db/development.sqlite3

development:
  adapter: mysql2
  encoding: utf8
  database: dev
  username: adminRKSPcAy
  password: 7veFbEg5qR_c
  host: localhost
  port: 3306

test:
  <<: *default
  database: db/test.sqlite3

production:
  adapter: mysql2
  encoding: utf8
  database: dev
  username: adminRKSPcAy
  password: 7veFbEg5qR_c
  host: localhost
  port: 3306



